/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author USUARIO UNO
 */
public class midPrincipal extends javax.swing.JFrame {
    private jpFormulario1 objFormulario1 = new jpFormulario1();
    private jpFormulario2 objFormulario2 = new jpFormulario2();
    private jpFormulario3 objFormulario3 = new jpFormulario3();
    private jpFormulario4 objFormulario4 = new jpFormulario4();
    private jpFormulario5 objFormulario5 = new jpFormulario5();
    private jpFormulario6 objFormulario6 = new jpFormulario6();
    
    private void inicializarFormularios(){
        jifFomulario1.setContentPane(objFormulario1);
        objFormulario1.setSize(300,300);
        jifFomulario1.setSize(300,300);
         
        jifFormulario2.setContentPane(objFormulario2);
        objFormulario2.setSize(300,300);
        jifFormulario2.setSize(300,300);
        
        jifFomulario3.setContentPane(objFormulario3);
        objFormulario3.setSize(300,300);
        jifFomulario3.setSize(300,300);
        
        jifFomulario4.setContentPane(objFormulario4);
        objFormulario4.setSize(300,300);
        jifFomulario4.setSize(300,300);
        
        jifFomulario5.setContentPane(objFormulario5);
        objFormulario5.setSize(300,300);
        jifFomulario5.setSize(300,300);
        
        jifFomulario6.setContentPane(objFormulario6);
        objFormulario6.setSize(300,300);
        jifFomulario6.setSize(300,300);
        }

    /**
     * Creates new form midPrincipal
     */
    public midPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifFomulario1 = new javax.swing.JInternalFrame();
        jifFormulario2 = new javax.swing.JInternalFrame();
        jifFomulario3 = new javax.swing.JInternalFrame();
        jifFomulario4 = new javax.swing.JInternalFrame();
        jifFomulario5 = new javax.swing.JInternalFrame();
        jifFomulario6 = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiFormaulario1 = new javax.swing.JMenuItem();
        jmiFormaulario2 = new javax.swing.JMenuItem();
        jmiFormaulario3 = new javax.swing.JMenuItem();
        jmiFormaulario4 = new javax.swing.JMenuItem();
        jmiFormaulario5 = new javax.swing.JMenuItem();
        jmiFormaulario6 = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFomulario1.setClosable(true);
        jifFomulario1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFomulario1.setVisible(false);

        javax.swing.GroupLayout jifFomulario1Layout = new javax.swing.GroupLayout(jifFomulario1.getContentPane());
        jifFomulario1.getContentPane().setLayout(jifFomulario1Layout);
        jifFomulario1Layout.setHorizontalGroup(
            jifFomulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFomulario1Layout.setVerticalGroup(
            jifFomulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFomulario1);
        jifFomulario1.setBounds(30, 30, 180, 170);

        jifFormulario2.setClosable(true);
        jifFormulario2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario2.setVisible(false);

        javax.swing.GroupLayout jifFormulario2Layout = new javax.swing.GroupLayout(jifFormulario2.getContentPane());
        jifFormulario2.getContentPane().setLayout(jifFormulario2Layout);
        jifFormulario2Layout.setHorizontalGroup(
            jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormulario2Layout.setVerticalGroup(
            jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormulario2);
        jifFormulario2.setBounds(220, 30, 170, 160);

        jifFomulario3.setClosable(true);
        jifFomulario3.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFomulario3.setVisible(false);

        javax.swing.GroupLayout jifFomulario3Layout = new javax.swing.GroupLayout(jifFomulario3.getContentPane());
        jifFomulario3.getContentPane().setLayout(jifFomulario3Layout);
        jifFomulario3Layout.setHorizontalGroup(
            jifFomulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFomulario3Layout.setVerticalGroup(
            jifFomulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFomulario3);
        jifFomulario3.setBounds(10, 180, 130, 100);

        jifFomulario4.setClosable(true);
        jifFomulario4.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFomulario4.setVisible(false);

        javax.swing.GroupLayout jifFomulario4Layout = new javax.swing.GroupLayout(jifFomulario4.getContentPane());
        jifFomulario4.getContentPane().setLayout(jifFomulario4Layout);
        jifFomulario4Layout.setHorizontalGroup(
            jifFomulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFomulario4Layout.setVerticalGroup(
            jifFomulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFomulario4);
        jifFomulario4.setBounds(140, 180, 130, 100);

        jifFomulario5.setClosable(true);
        jifFomulario5.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFomulario5.setVisible(false);

        javax.swing.GroupLayout jifFomulario5Layout = new javax.swing.GroupLayout(jifFomulario5.getContentPane());
        jifFomulario5.getContentPane().setLayout(jifFomulario5Layout);
        jifFomulario5Layout.setHorizontalGroup(
            jifFomulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFomulario5Layout.setVerticalGroup(
            jifFomulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFomulario5);
        jifFomulario5.setBounds(270, 180, 120, 100);

        jifFomulario6.setClosable(true);
        jifFomulario6.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFomulario6.setVisible(false);

        javax.swing.GroupLayout jifFomulario6Layout = new javax.swing.GroupLayout(jifFomulario6.getContentPane());
        jifFomulario6.getContentPane().setLayout(jifFomulario6Layout);
        jifFomulario6Layout.setHorizontalGroup(
            jifFomulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFomulario6Layout.setVerticalGroup(
            jifFomulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFomulario6);
        jifFomulario6.setBounds(140, 90, 130, 90);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jmiFormaulario1.setMnemonic('s');
        jmiFormaulario1.setText("Formulario 1");
        jmiFormaulario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario1ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario1);

        jmiFormaulario2.setMnemonic('a');
        jmiFormaulario2.setText("Formulario 2");
        jmiFormaulario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario2ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario2);

        jmiFormaulario3.setText("Formulario 3");
        jmiFormaulario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario3ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario3);

        jmiFormaulario4.setText("Formulario 4");
        jmiFormaulario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario4ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario4);

        jmiFormaulario5.setText("Formulario 5");
        jmiFormaulario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario5ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario5);

        jmiFormaulario6.setText("Formulario 6");
        jmiFormaulario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormaulario6ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormaulario6);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Exit");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormaulario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario1ActionPerformed
jifFomulario1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiFormaulario1ActionPerformed

    private void jmiFormaulario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario2ActionPerformed
jifFormulario2.setVisible(true); 
    }//GEN-LAST:event_jmiFormaulario2ActionPerformed

    private void jmiFormaulario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario3ActionPerformed
jifFomulario3.setVisible(true); 
    }//GEN-LAST:event_jmiFormaulario3ActionPerformed

    private void jmiFormaulario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario4ActionPerformed
jifFomulario4.setVisible(true); 
    }//GEN-LAST:event_jmiFormaulario4ActionPerformed

    private void jmiFormaulario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario5ActionPerformed
jifFomulario5.setVisible(true); 
    }//GEN-LAST:event_jmiFormaulario5ActionPerformed

    private void jmiFormaulario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormaulario6ActionPerformed
jifFomulario6.setVisible(true); 
    }//GEN-LAST:event_jmiFormaulario6ActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new midPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JInternalFrame jifFomulario1;
    private javax.swing.JInternalFrame jifFomulario3;
    private javax.swing.JInternalFrame jifFomulario4;
    private javax.swing.JInternalFrame jifFomulario5;
    private javax.swing.JInternalFrame jifFomulario6;
    private javax.swing.JInternalFrame jifFormulario2;
    private javax.swing.JMenuItem jmiFormaulario1;
    private javax.swing.JMenuItem jmiFormaulario2;
    private javax.swing.JMenuItem jmiFormaulario3;
    private javax.swing.JMenuItem jmiFormaulario4;
    private javax.swing.JMenuItem jmiFormaulario5;
    private javax.swing.JMenuItem jmiFormaulario6;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
